[program:pi0_audit]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/pi0_audit.sh
autostart=false
autorestart=false
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
